#!/bin/bash

if [[ -d dstemp ]] 
then 
	echo "Are you sure to overwrite dstemp? (y/n)"
	read ANS
	if [[ "$ANS" = "y" || "$ANS" = "yes" ]]
	then
		rm -fr dstemp
	elif [[ "$ANS" = "n" || "$ANS" = "no" ]]
	then
		exit
	else
		echo "answer in (y/n)"
		exit
	fi
fi
sudo apt-get install bison flex indent
tar xvf .downloads/disksim-4.0.tar
mv disksim-4.0 dstemp
cd dstemp
#cp -dir ../.downloads/ssd-add-on/ssdmodel ./
tar xvf ../.downloads/ssd-add-on.tar
mv ./ssd-add-on/ssdmodel ./
rm -fr ssd-add-on
#rm -fr SSD\ Extension\ for\ DiskSim\ Simulation\ Environment\ EULA\ for\ CPT\ \(2008-10-06\).txt
patch -p1 < ssdmodel/ssd-patch
patch -p1 < ../.downloads/make-patch
#cp -dir ../.downloads/test ./
tar xvf ../.downloads/test.tar
chmod 777 ./test/run
make
cd ssdmodel/valid
chmod 777 runvalid
echo "
***************************************************
Installation and patch is done.
Testing validity using \"./ssdmodel/valid/runvalid\".
***************************************************
"
./runvalid
