#!/bin/sh

cp $1/Makefile $2/Makefile
cp $1/src/disksim_global.h $2/src/disksim_global.h
cp $1/src/disksim.c $2/src/disksim.c
cp $1/ssdmodel/Makefile $2/ssdmodel/Makefile
cp $1/ssdmodel/adivim.h $2/ssdmodel/adivim.h
cp $1/ssdmodel/adivim.c $2/ssdmodel/adivim.c
cp $1/ssdmodel/ssd.h $2/ssdmodel/ssd.h
cp $1/ssdmodel/ssd.c $2/ssdmodel/ssd.c
cp $1/ssdmodel/ssd_clean.h $2/ssdmodel/ssd_clean.h
cp $1/ssdmodel/ssd_clean.c $2/ssdmodel/ssd_clean.c
cp $1/ssdmodel/ssd_timing.h $2/ssdmodel/ssd_timing.h
cp $1/ssdmodel/ssd_timing.c $2/ssdmodel/ssd_timing.c
cp $1/ssdmodel/ssd_init.h $2/ssdmodel/ssd_init.h
cp $1/ssdmodel/ssd_init.c $2/ssdmodel/ssd_init.c
cp $1/test/study.trace $2/test/study.trace
cp $1/test/run $2/test/run
cp $1/test/diskmon_desktop.log $2/test/diskmon_desktop.log
cp $1/test/explorer_1.log $2/test/explorer_1.log
cp $1/test/iozone_all.log $2/test/iozone_all.log
cp $1/test/jpeg_copy_2gb_ntfs.log $2/test/jpeg_copy_2gb_ntfs.log
cp $1/test/office2007_install_ntfs.log $2/test/office2007_install_ntfs.log

cd $2
clear; clear; make | grep error

cd test
./run $3