# Disksim SSD ADIVIM support
# ©2012 Seoul National University lecture project1 ADIVIM PROJECT team. All right reserved.

# Need to make it enables other files to include "disksim_global.h" and other header files.